# yaml-language-server: https://github.com/espanso/espanso/blob/dev/schemas/match.schema.json

# OASIS-IS ChatGPT framework Form.  OASIS-IS stands for : O-bjective, A-rchetype, -S-etting, I-llustrations, S-tyle, - , I-nterpretation, S-pecification.
# After those steps you move to Evaluate - How good was the response, give your chatbot feedback, and then Banter - Continue the conversation.  
# Paid ChatGPT users can use the current list of models available while unpaid can use the default model.
# The frameworks spreadsheet can be found here: http://3dmkf.com/pace-oasis
# This first one, is meant to generate a prompt.  Run :oasis from a URL in a web browser, fill out the form and submit it, then press enter.  It will pass the prompt to Chat
global_vars:
  - name: urlprompt
    type: echo
    params:
      echo: "Title: {{oasisform.title}}%0AYou will use the OASIS IS model to start a conversation.%0A1) Objective: What do you wish to accomplish?%0A2) Archetype: Persona, identity, character, or profile.  This can be generic like a manager with 20 years workplace mediation experience, or specific like Batman, Mark Twain, or Jack Sparrow.%0A3) Setting: Context or background information.%0A4) Illustrations: These are your examples. This is Optional.%0A5) Style: The tone, mood, or voice.  Examples: comedic, formal, casual, business casual.%0A6) Interpretation: Output Framework or Structure.%0A7) Specification: This is the output style, format, or how the output should look like.  Examples: Table, List, Paragraph, Code Block, etc.%0A%0A
        Title: {{oasisform.title}} / Model: {{oasisform.model}}%0A
        1) What I want you to accomplish: {{oasisform.objective}}%0A
        2) Using this persona: {{oasisform.archetype}}%0A
        3) Here is additional Context: {{oasisform.setting}}%0A
        4) Here are Examples: {{oasisform.illustrations}}%0A
        5) Tone/Mode/Voice: {{oasisform.style}}%0A
        6) I want the output to follow this output framework: {{oasisform.interpretation}}%0A
        7) Output should look like: {{oasisform.specification}}%0A
        &model={{oasisform.model}}"
  - name: boxprompt
    type: echo
    params:
      echo: "Title: {{oasisform.title}}\nYou will use the OASIS IS model to start a conversation.\n1) Objective: What do you wish to accomplish?\n2)Archetype: Persona, identity, character, or profile.  This can be generic like a manager with 20 years workplace mediation experience, or specific like Batman, Mark Twain, or Jack Sparrow.\n3) Setting: Context or background information.\n4) Illustrations: These are your examples. This is Optional.\n5) Style: The tone, mood, or voice.  Examples: comedic, formal, casual, business casual.\n6) Interpretation: Output Framework or Structure.\n7) Specification: This is the output style, format, or how the output should look like.  Examples: Table, List, Paragraph, Code Block, etc.\n\n
        Title: {{oasisform.title}}\n
        1) What I want you to accomplish: {{oasisform.objective}}\n
        2) Using this persona: {{oasisform.archetype}}\n
        3) Here is additional Context: {{oasisform.setting}}\n
        4) Here are Examples: {{oasisform.illustrations}}\n
        5) Tone/Mode/Voice: {{oasisform.style}}\n
        6) I want the output to follow this output framework: {{oasisform.interpretation}}\n
        7) Output should look like: {{oasisform.specification}}\n"
  - name: formo1
    type: echo
    params:
      echo: "You will need to fill out the following 7 fields. The more you fill out the better the prompt will be.  Except for Objective, they are all optional.\n
        CONVERSATION TITLE: Name your Chat (This can help you find it later, it does not name it on the left)[[title]]\n
        1) Objective: 	What do you want to accomplish:\n
        [[objective]]\n
        2) Archetype: 	Persona, identity, character, or profile.  This can be generic like a manager with 20 years workplace mediation experience, or specific like Batman, Mark Twain, or Jack Sparrow:\n
        [[archetype]]\n
        3) Setting: 	Context or background information:\n
        [[setting]]\n
        4) Illustrations: 	These are your examples:\n
        [[illustrations]]\n
        5) Style:   The tone, mood, or voice.  Examples: comedic, formal, casual, business casual:\n
        [[style]]\n
        6) Interpretation:    Output Framework or Structure: [[interpretation]]\n
        7) Specification:   This is the output style, format, or how the output should look like.  Examples: Table, List, Paragraph, Code Block, etc:\n
        [[specification]]\n"


anchors:
  - &formfields
      title:
      multiline: false
      objective:
        multiline: true
      archetype:
      setting:
        multiline: true
      illustrations:
        multiline: true
      style:
      interpretation: 
        type: choice
        default: No Framework
        values:
          - No Framework
          - 4Ps (Product, Price, Place, Promotion)
          - 5 Rights of Nursing Delegation
          - 5 Whys
          - 5Ws (Who, What, Where, When, Why) & 1H (How)
          - ACE (Attention, Connection, Engagement)
          - Agile Framework
          - AIDA (Attention, Interest, Desire, Action)
          - Ansoff Matrix
          - Balanced Scorecard
          - Blue Ocean Strategy
          - Business Model Canvas
          - C.A.R.L. method - Context, Action, Results, Learning
          - Claim-Evidence-Reasoning Framework (CER)
          - Dan Harmon's Story Circle
          - DMAIC (Define, Measure, Analyze, Improve, Control)
          - Eisenhower Box (Urgent-Important Matrix)
          - Executive Summaries
          - Fishbone Diagram (Ishikawa Diagram)
          - Five Paragraph Order Planning and Execution
          - Freytag's Pyramid / 5 - point Story Structure
          - GAP Analysis
          - HERO (Hook, Empathy, Response, Offer)
          - Inverted Pyramid
          - Kano Model
          - Literary Story Format - Narrative Structure
          - Monroe's Motivated Sequence
          - MoSCoW Method
          - MOST (Mission, Objectives, Strategies, Tactics)
          - OKR (Objectives and Key Results)
          - PAPA (Problem, Agitation, Persuasion, Action)
          - Pareto Analysis (80/20 Rule)
          - PASO (Problem, Agitation, Solution, Outcome)
          - PDCA (Plan, Do, Check, Act)
          - PEEC (Point, Evidence, Explanation, Conclusion)
          - PESTLE Analysis (Political, Economic, Social, Technological, Legal and Environmental)
          - Porter's Five Forces
          - QUEST (Qualify, Understand, Educate, Stimulate, Transition)
          - R.C.S. method - Rephrase, Clarify, and Structure
          - RACI (Responsible, Accountable, Consulted, Informed)
          - ROIC (Return on Invested Capital) analysis
          - S.T.A.R. method - Situation, Task, Action, Results
          - Save The Cat Beat Sheet
          - Six Sigma
          - Six Thinking Hats
          - SLAP (Situation, Language, Action, Purpose)
          - SMART (Specific, Measurable, Achievable, Relevant, Time-bound)
          - SOAR Analysis
          - SWOT Analysis
          - The 10-20-30 Rule
          - The 22 Rules of Storytelling According to Pixar
          - The 8 Sequences Method
          - The Fichtean Curve
          - The Hero's Journey (Monomyth)
          - The Hourglass Format
          - The Lead-Quote-Commentary (LQC) Format
          - The Narrative Structure in Business and Marketing
          - The Novel Roadmap
          - The Seven-Point Story Structure
          - The Snowflake Method
          - The Wall Street Journal Formula
          - Theory of Constraints
          - Three-Act Structure
          - Three-Part Presentation Structure
          - Todorov's Narrative Theory
          - TOWS Matrix
          - USP (Unique Selling Proposition)
          - Value Chain Analysis
          - Value Net Analysis
          - Value Proposition Canvas
          - VRIO (Value, Rarity, Imitability, and Organization) Analysis
          - Waterfall Model
      specification:
      model:
        type: choice
        default: gpt-4o
        values:
          - gpt-4o
          - gpt-4o-mini
          - gpt-4

matches:  
  - trigger: :oasis
    replace: https://chatgpt.com/chat?q={{urlprompt}}
    vars: 
      - name: "oasisform"
        type: form
        params:
          layout: |
            "{{formo1}}"
            Model: [[model]]
          fields: 
            *formfields

  # As the form above, this is meant to create a prompt using the OASIS-IS model.  This is meant to be used in the prompt field of the Chatbot form.  Unlike the one above, this one will work for any model.
  # poasis is short for prompt-oasis.  

  - trigger: :poasis
    replace: "{{boxprompt}}"
    vars: 
      - name: "oasisform"
        type: form
        params:
          layout: |
            "{{formo1}}"
          fields: 
            *formfields
