global_vars:
  - name: "clipboard"
    type: "clipboard"

matches:

  ### Go
  # https://golangci-lint.run/usage/false-positives/#nolint-directive
  - trigger: "/nol"
    replace: "//nolint:{{clipboard}}"
  - trigger: "/noa"
    replace: "//nolint:all"

  ### Ruby
  # https://docs.rubocop.org/rubocop/configuration.html#disabling-cops-within-source-code
  - trigger: "#rcd"
    replace: "# rubocop:disable {{clipboard}}"
  - trigger: "#rce"
    replace: "# rubocop:enable {{clipboard}}"
  - trigger: "#rct"
    replace: "# rubocop:todo {{clipboard}}"

  ### Rust
  # https://doc.rust-lang.org/stable/clippy/usage.html#lint-configuration
  # https://github.com/rust-lang/rust-clippy?tab=readme-ov-file#allowingdenying-lints
  - trigger: "#cla"
    replace: "#[allow({{clipboard}})]"
  - trigger: "#clw"
    replace: "#[warn({{clipboard}})]"
  - trigger: "#cld"
    replace: "#[deny({{clipboard}})]"
  - trigger: "#clp"
    replace: "#![deny(clippy::pedantic)]" # prone to false positives!

  ### Shell
  # https://github.com/koalaman/shellcheck/blob/master/shellcheck.1.md#directives
  - trigger: "#scd"
    replace: "# shellcheck disable={{clipboard}}"
