# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

global_vars:
  # OS-agnostic derivation of path to CSV file.
  - name: urlcsv
    type: script
    params:
      args:
        - python
        - -c
        - |
          import os
          config_path = os.getenv("CONFIG")
          print(os.path.join(config_path, "match", "packages", "form-list", "form_urls.csv"))
      
matches:
  - trigger: :forms
    replace: '{{form_url}}'
    vars:
      # Read choice-list options from CSV file.
      - name: form_names
        type: script
        params:
          args:
            - python
            - -c
            - |
              import csv
              with open(r'{{urlcsv}}', newline='') as f:
                for row in csv.reader(f): print(row[0])
      # Form
      - name: choice
        type: form
        params:
          layout: |
            Get link for:
            [[choices]]
          fields:
            choices:
              type: list
              values: '{{form_names}}'
      # Return paired item as selected above
      - name: form_url
        type: script
        params:
          args:
            - python
            - -c
            - |
              import csv
              with open(r'{{urlcsv}}', newline='') as f:
                for row in csv.reader(f):
                  if row[0] == '{{choice.choices}}':
                    print(row[1]) ; break
