matches:
  - trigger: ":slate50"
    replace: "#f8fafc"
  - trigger: ":slate100"
    replace: "#f1f5f9"
  - trigger: ":slate200"
    replace: "#e2e8f0"
  - trigger: ":slate300"
    replace: "#cbd5e1"
  - trigger: ":slate400"
    replace: "#94a3b8"
  - trigger: ":slate500"
    replace: "#64748b"
  - trigger: ":slate600"
    replace: "#475569"
  - trigger: ":slate700"
    replace: "#334155"
  - trigger: ":slate800"
    replace: "#1e293b"
  - trigger: ":slate900"
    replace: "#0f172a"
  - trigger: ":slate950"
    replace: "#020617"

  - trigger: ":gray50"
    replace: "#f9fafb"
  - trigger: ":gray100"
    replace: "#f3f4f6"
  - trigger: ":gray200"
    replace: "#e5e7eb"
  - trigger: ":gray300"
    replace: "#d1d5db"
  - trigger: ":gray400"
    replace: "#9ca3af"
  - trigger: ":gray500"
    replace: "#6b7280"
  - trigger: ":gray600"
    replace: "#4b5563"
  - trigger: ":gray700"
    replace: "#374151"
  - trigger: ":gray800"
    replace: "#1f2937"
  - trigger: ":gray900"
    replace: "#111827"
  - trigger: ":gray950"
    replace: "#030712"

  - trigger: ":zinc50"
    replace: "#fafafa"
  - trigger: ":zinc100"
    replace: "#f4f4f5"
  - trigger: ":zinc200"
    replace: "#e4e4e7"
  - trigger: ":zinc300"
    replace: "#d4d4d8"
  - trigger: ":zinc400"
    replace: "#a1a1aa"
  - trigger: ":zinc500"
    replace: "#71717a"
  - trigger: ":zinc600"
    replace: "#52525b"
  - trigger: ":zinc700"
    replace: "#3f3f46"
  - trigger: ":zinc800"
    replace: "#27272a"
  - trigger: ":zinc900"
    replace: "#18181b"
  - trigger: ":zinc950"
    replace: "#09090b"

  - trigger: ":neutral50"
    replace: "#fafafa"
  - trigger: ":neutral100"
    replace: "#f5f5f5"
  - trigger: ":neutral200"
    replace: "#e5e5e5"
  - trigger: ":neutral300"
    replace: "#d4d4d4"
  - trigger: ":neutral400"
    replace: "#a3a3a3"
  - trigger: ":neutral500"
    replace: "#737373"
  - trigger: ":neutral600"
    replace: "#525252"
  - trigger: ":neutral700"
    replace: "#404040"
  - trigger: ":neutral800"
    replace: "#262626"
  - trigger: ":neutral900"
    replace: "#171717"
  - trigger: ":neutral950"
    replace: "#0a0a0a"

  - trigger: ":stone50"
    replace: "#fafaf9"
  - trigger: ":stone100"
    replace: "#f5f5f4"
  - trigger: ":stone200"
    replace: "#e7e5e4"
  - trigger: ":stone300"
    replace: "#d6d3d1"
  - trigger: ":stone400"
    replace: "#a8a29e"
  - trigger: ":stone500"
    replace: "#78716c"
  - trigger: ":stone600"
    replace: "#57534e"
  - trigger: ":stone700"
    replace: "#44403c"
  - trigger: ":stone800"
    replace: "#292524"
  - trigger: ":stone900"
    replace: "#1c1917"
  - trigger: ":stone950"
    replace: "#0c0a09"

  - trigger: ":red50"
    replace: "#fef2f2"
  - trigger: ":red100"
    replace: "#fee2e2"
  - trigger: ":red200"
    replace: "#fecaca"
  - trigger: ":red300"
    replace: "#fca5a5"
  - trigger: ":red400"
    replace: "#f87171"
  - trigger: ":red500"
    replace: "#ef4444"
  - trigger: ":red600"
    replace: "#dc2626"
  - trigger: ":red700"
    replace: "#b91c1c"
  - trigger: ":red800"
    replace: "#991b1b"
  - trigger: ":red900"
    replace: "#7f1d1d"
  - trigger: ":red950"
    replace: "#450a0a"

  - trigger: ":orange50"
    replace: "#fff7ed"
  - trigger: ":orange100"
    replace: "#ffedd5"
  - trigger: ":orange200"
    replace: "#fed7aa"
  - trigger: ":orange300"
    replace: "#fdba74"
  - trigger: ":orange400"
    replace: "#fb923c"
  - trigger: ":orange500"
    replace: "#f97316"
  - trigger: ":orange600"
    replace: "#ea580c"
  - trigger: ":orange700"
    replace: "#c2410c"
  - trigger: ":orange800"
    replace: "#9a3412"
  - trigger: ":orange900"
    replace: "#7c2d12"
  - trigger: ":orange950"
    replace: "#431407"

  - trigger: ":amber50"
    replace: "#fffbeb"
  - trigger: ":amber100"
    replace: "#fef3c7"
  - trigger: ":amber200"
    replace: "#fde68a"
  - trigger: ":amber300"
    replace: "#fcd34d"
  - trigger: ":amber400"
    replace: "#fbbf24"
  - trigger: ":amber500"
    replace: "#f59e0b"
  - trigger: ":amber600"
    replace: "#d97706"
  - trigger: ":amber700"
    replace: "#b45309"
  - trigger: ":amber800"
    replace: "#92400e"
  - trigger: ":amber900"
    replace: "#78350f"
  - trigger: ":amber950"
    replace: "#451a03"

  - trigger: ":yellow50"
    replace: "#fefce8"
  - trigger: ":yellow100"
    replace: "#fef9c3"
  - trigger: ":yellow200"
    replace: "#fef08a"
  - trigger: ":yellow300"
    replace: "#fde047"
  - trigger: ":yellow400"
    replace: "#facc15"
  - trigger: ":yellow500"
    replace: "#eab308"
  - trigger: ":yellow600"
    replace: "#ca8a04"
  - trigger: ":yellow700"
    replace: "#a16207"
  - trigger: ":yellow800"
    replace: "#854d0e"
  - trigger: ":yellow900"
    replace: "#713f12"
  - trigger: ":yellow950"
    replace: "#422006"

  - trigger: ":lime50"
    replace: "#f7fee7"
  - trigger: ":lime100"
    replace: "#ecfccb"
  - trigger: ":lime200"
    replace: "#d9f99d"
  - trigger: ":lime300"
    replace: "#bef264"
  - trigger: ":lime400"
    replace: "#a3e635"
  - trigger: ":lime500"
    replace: "#84cc16"
  - trigger: ":lime600"
    replace: "#65a30d"
  - trigger: ":lime700"
    replace: "#4d7c0f"
  - trigger: ":lime800"
    replace: "#3f6212"
  - trigger: ":lime900"
    replace: "#365314"
  - trigger: ":lime950"
    replace: "#1a2e05"

  - trigger: ":green50"
    replace: "#f0fdf4"
  - trigger: ":green100"
    replace: "#dcfce7"
  - trigger: ":green200"
    replace: "#bbf7d0"
  - trigger: ":green300"
    replace: "#86efac"
  - trigger: ":green400"
    replace: "#4ade80"
  - trigger: ":green500"
    replace: "#22c55e"
  - trigger: ":green600"
    replace: "#16a34a"
  - trigger: ":green700"
    replace: "#15803d"
  - trigger: ":green800"
    replace: "#166534"
  - trigger: ":green900"
    replace: "#14532d"
  - trigger: ":green950"
    replace: "#052e16"

  - trigger: ":emerald50"
    replace: "#ecfdf5"
  - trigger: ":emerald100"
    replace: "#d1fae5"
  - trigger: ":emerald200"
    replace: "#a7f3d0"
  - trigger: ":emerald300"
    replace: "#6ee7b7"
  - trigger: ":emerald400"
    replace: "#34d399"
  - trigger: ":emerald500"
    replace: "#10b981"
  - trigger: ":emerald600"
    replace: "#059669"
  - trigger: ":emerald700"
    replace: "#047857"
  - trigger: ":emerald800"
    replace: "#065f46"
  - trigger: ":emerald900"
    replace: "#064e3b"
  - trigger: ":emerald950"
    replace: "#022c22"

  - trigger: ":teal50"
    replace: "#f0fdfa"
  - trigger: ":teal100"
    replace: "#ccfbf1"
  - trigger: ":teal200"
    replace: "#99f6e4"
  - trigger: ":teal300"
    replace: "#5eead4"
  - trigger: ":teal400"
    replace: "#2dd4bf"
  - trigger: ":teal500"
    replace: "#14b8a6"
  - trigger: ":teal600"
    replace: "#0d9488"
  - trigger: ":teal700"
    replace: "#0f766e"
  - trigger: ":teal800"
    replace: "#115e59"
  - trigger: ":teal900"
    replace: "#134e4a"
  - trigger: ":teal950"
    replace: "#042f2e"

  - trigger: ":cyan50"
    replace: "#ecfeff"
  - trigger: ":cyan100"
    replace: "#cffafe"
  - trigger: ":cyan200"
    replace: "#a5f3fc"
  - trigger: ":cyan300"
    replace: "#67e8f9"
  - trigger: ":cyan400"
    replace: "#22d3ee"
  - trigger: ":cyan500"
    replace: "#06b6d4"
  - trigger: ":cyan600"
    replace: "#0891b2"
  - trigger: ":cyan700"
    replace: "#0e7490"
  - trigger: ":cyan800"
    replace: "#155e75"
  - trigger: ":cyan900"
    replace: "#164e63"
  - trigger: ":cyan950"
    replace: "#083344"

  - trigger: ":sky50"
    replace: "#f0f9ff"
  - trigger: ":sky100"
    replace: "#e0f2fe"
  - trigger: ":sky200"
    replace: "#bae6fd"
  - trigger: ":sky300"
    replace: "#7dd3fc"
  - trigger: ":sky400"
    replace: "#38bdf8"
  - trigger: ":sky500"
    replace: "#0ea5e9"
  - trigger: ":sky600"
    replace: "#0284c7"
  - trigger: ":sky700"
    replace: "#0369a1"
  - trigger: ":sky800"
    replace: "#075985"
  - trigger: ":sky900"
    replace: "#0c4a6e"
  - trigger: ":sky950"
    replace: "#082f49"

  - trigger: ":blue50"
    replace: "#eff6ff"
  - trigger: ":blue100"
    replace: "#dbeafe"
  - trigger: ":blue200"
    replace: "#bfdbfe"
  - trigger: ":blue300"
    replace: "#93c5fd"
  - trigger: ":blue400"
    replace: "#60a5fa"
  - trigger: ":blue500"
    replace: "#3b82f6"
  - trigger: ":blue600"
    replace: "#2563eb"
  - trigger: ":blue700"
    replace: "#1d4ed8"
  - trigger: ":blue800"
    replace: "#1e40af"
  - trigger: ":blue900"
    replace: "#1e3a8a"
  - trigger: ":blue950"
    replace: "#172554"

  - trigger: ":indigo50"
    replace: "#eef2ff"
  - trigger: ":indigo100"
    replace: "#e0e7ff"
  - trigger: ":indigo200"
    replace: "#c7d2fe"
  - trigger: ":indigo300"
    replace: "#a5b4fc"
  - trigger: ":indigo400"
    replace: "#818cf8"
  - trigger: ":indigo500"
    replace: "#6366f1"
  - trigger: ":indigo600"
    replace: "#4f46e5"
  - trigger: ":indigo700"
    replace: "#4338ca"
  - trigger: ":indigo800"
    replace: "#3730a3"
  - trigger: ":indigo900"
    replace: "#312e81"
  - trigger: ":indigo950"
    replace: "#1e1b4b"

  - trigger: ":violet50"
    replace: "#f5f3ff"
  - trigger: ":violet100"
    replace: "#ede9fe"
  - trigger: ":violet200"
    replace: "#ddd6fe"
  - trigger: ":violet300"
    replace: "#c4b5fd"
  - trigger: ":violet400"
    replace: "#a78bfa"
  - trigger: ":violet500"
    replace: "#8b5cf6"
  - trigger: ":violet600"
    replace: "#7c3aed"
  - trigger: ":violet700"
    replace: "#6d28d9"
  - trigger: ":violet800"
    replace: "#5b21b6"
  - trigger: ":violet900"
    replace: "#4c1d95"
  - trigger: ":violet950"
    replace: "#2e1065"

  - trigger: ":purple50"
    replace: "#faf5ff"
  - trigger: ":purple100"
    replace: "#f3e8ff"
  - trigger: ":purple200"
    replace: "#e9d5ff"
  - trigger: ":purple300"
    replace: "#d8b4fe"
  - trigger: ":purple400"
    replace: "#c084fc"
  - trigger: ":purple500"
    replace: "#a855f7"
  - trigger: ":purple600"
    replace: "#9333ea"
  - trigger: ":purple700"
    replace: "#7e22ce"
  - trigger: ":purple800"
    replace: "#6b21a8"
  - trigger: ":purple900"
    replace: "#581c87"
  - trigger: ":purple950"
    replace: "#3b0764"

  - trigger: ":fuchsia50"
    replace: "#fdf4ff"
  - trigger: ":fuchsia100"
    replace: "#fae8ff"
  - trigger: ":fuchsia200"
    replace: "#f5d0fe"
  - trigger: ":fuchsia300"
    replace: "#f0abfc"
  - trigger: ":fuchsia400"
    replace: "#e879f9"
  - trigger: ":fuchsia500"
    replace: "#d946ef"
  - trigger: ":fuchsia600"
    replace: "#c026d3"
  - trigger: ":fuchsia700"
    replace: "#a21caf"
  - trigger: ":fuchsia800"
    replace: "#86198f"
  - trigger: ":fuchsia900"
    replace: "#701a75"
  - trigger: ":fuchsia950"
    replace: "#4a044e"

  - trigger: ":pink50"
    replace: "#fdf2f8"
  - trigger: ":pink100"
    replace: "#fce7f3"
  - trigger: ":pink200"
    replace: "#fbcfe8"
  - trigger: ":pink300"
    replace: "#f9a8d4"
  - trigger: ":pink400"
    replace: "#f472b6"
  - trigger: ":pink500"
    replace: "#ec4899"
  - trigger: ":pink600"
    replace: "#db2777"
  - trigger: ":pink700"
    replace: "#be185d"
  - trigger: ":pink800"
    replace: "#9d174d"
  - trigger: ":pink900"
    replace: "#831843"
  - trigger: ":pink950"
    replace: "#500724"

  - trigger: ":rose50"
    replace: "#fff1f2"
  - trigger: ":rose100"
    replace: "#ffe4e6"
  - trigger: ":rose200"
    replace: "#fecdd3"
  - trigger: ":rose300"
    replace: "#fda4af"
  - trigger: ":rose400"
    replace: "#fb7185"
  - trigger: ":rose500"
    replace: "#f43f5e"
  - trigger: ":rose600"
    replace: "#e11d48"
  - trigger: ":rose700"
    replace: "#be123c"
  - trigger: ":rose800"
    replace: "#9f1239"
  - trigger: ":rose900"
    replace: "#881337"
  - trigger: ":rose950"
    replace: "#4c0519"
