global_vars:      
  - name: autorname
    type: echo
    params: 
      echo: YourName
matches:
  - trigger: ":newpost"
    replace: "---\ndate: {{mydate}}\nauthor: {{autorname}}\ntags:\ncategory:\ntitle:\n---"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"