matches:
  - trigger: "ain't"
    replace: "am not"
    word: true
    propagate_case: true

  - trigger: "ain't"
    replace: "are not"
    word: true
    propagate_case: true

  - trigger: "ain't"
    replace: "is not"
    word: true
    propagate_case: true

  - trigger: "aren't"
    replace: "are not"
    word: true
    propagate_case: true

  - trigger: "can't"
    replace: "cannot"
    word: true
    propagate_case: true

  - trigger: "couldn't"
    replace: "could not"
    word: true
    propagate_case: true

  - trigger: "didn't"
    replace: "did not"
    word: true
    propagate_case: true

  - trigger: "doesn't"
    replace: "does not"
    word: true
    propagate_case: true

  - trigger: "don't"
    replace: "do not"
    word: true
    propagate_case: true

  - trigger: "hadn't"
    replace: "had not"
    word: true
    propagate_case: true

  - trigger: "hasn't"
    replace: "has not"
    word: true
    propagate_case: true

  - trigger: "haven't"
    replace: "have not"
    word: true
    propagate_case: true

  - trigger: "he'd"
    replace: "he had"
    word: true
    propagate_case: true

  - trigger: "he'd"
    replace: "he would"
    word: true
    propagate_case: true

  - trigger: "he'll"
    replace: "he shall"
    word: true
    propagate_case: true

  - trigger: "he'll"
    replace: "he will"
    word: true
    propagate_case: true

  - trigger: "he's"
    replace: "he is"
    word: true
    propagate_case: true

  - trigger: "here's"
    replace: "here is"
    word: true
    propagate_case: true

  - trigger: "how's"
    replace: "how is"
    word: true
    propagate_case: true

  - trigger: "I'd"
    replace: "I had"
    word: true
    propagate_case: true

  - trigger: "I'd"
    replace: "I would"
    word: true
    propagate_case: true

  - trigger: "I'll"
    replace: "I shall"
    word: true
    propagate_case: true

  - trigger: "I'll"
    replace: "I will"
    word: true
    propagate_case: true

  - trigger: "I'm"
    replace: "I am"
    word: true
    propagate_case: true

  - trigger: "I've"
    replace: "I have"
    word: true
    propagate_case: true

  - trigger: "isn't"
    replace: "is not"
    word: true
    propagate_case: true

  - trigger: "it'll"
    replace: "it will"
    word: true
    propagate_case: true

  - trigger: "it's"
    replace: "it is"
    word: true
    propagate_case: true

  - trigger: "let's"
    replace: "let us"
    word: true
    propagate_case: true

  - trigger: "mightn't"
    replace: "might not"
    word: true
    propagate_case: true

  - trigger: "mustn't"
    replace: "must not"
    word: true
    propagate_case: true

  - trigger: "she'd"
    replace: "she had"
    word: true
    propagate_case: true

  - trigger: "she'd"
    replace: "she would"
    word: true
    propagate_case: true

  - trigger: "she'll"
    replace: "she shall"
    word: true
    propagate_case: true

  - trigger: "she'll"
    replace: "she will"
    word: true
    propagate_case: true

  - trigger: "she's"
    replace: "she is"
    word: true
    propagate_case: true

  - trigger: "shouldn't"
    replace: "should not"
    word: true
    propagate_case: true

  - trigger: "should've"
    replace: "should have"
    word: true
    propagate_case: true

  - trigger: "that's"
    replace: "that is"
    word: true
    propagate_case: true

  - trigger: "there's"
    replace: "there is"
    word: true
    propagate_case: true

  - trigger: "they'd"
    replace: "they had"
    word: true
    propagate_case: true

  - trigger: "they'd"
    replace: "they would"
    word: true
    propagate_case: true

  - trigger: "they'll"
    replace: "they shall"
    word: true
    propagate_case: true

  - trigger: "they'll"
    replace: "they will"
    word: true
    propagate_case: true

  - trigger: "they're"
    replace: "they are"
    word: true
    propagate_case: true

  - trigger: "they've"
    replace: "they have"
    word: true
    propagate_case: true

  - trigger: "we'd"
    replace: "we had"
    word: true
    propagate_case: true

  - trigger: "we'd"
    replace: "we would"
    word: true
    propagate_case: true

  - trigger: "we'll"
    replace: "we shall"
    word: true
    propagate_case: true

  - trigger: "we'll"
    replace: "we will"
    word: true
    propagate_case: true

  - trigger: "we're"
    replace: "we are"
    word: true
    propagate_case: true

  - trigger: "we've"
    replace: "we have"
    word: true
    propagate_case: true

  - trigger: "weren't"
    replace: "were not"
    word: true
    propagate_case: true

  - trigger: "what's"
    replace: "what is"
    word: true
    propagate_case: true

  - trigger: "when's"
    replace: "when is"
    word: true
    propagate_case: true

  - trigger: "where's"
    replace: "where is"
    word: true
    propagate_case: true

  - trigger: "who's"
    replace: "who is"
    word: true
    propagate_case: true

  - trigger: "won't"
    replace: "will not"
    word: true
    propagate_case: true

  - trigger: "wouldn't"
    replace: "would not"
    word: true
    propagate_case: true

  - trigger: "would've"
    replace: "would have"
    word: true
    propagate_case: true

  - trigger: "you'd"
    replace: "you had"
    word: true
    propagate_case: true

  - trigger: "you'd"
    replace: "you would"
    word: true
    propagate_case: true

  - trigger: "you'll"
    replace: "you shall"
    word: true
    propagate_case: true

  - trigger: "you'll"
    replace: "you will"
    word: true
    propagate_case: true

  - trigger: "you're"
    replace: "you are"
    word: true
    propagate_case: true

  - trigger: "you've"
    replace: "you have"
    word: true
    propagate_case: true
